### ISSUE TITLE
*randomnumber : pas d'autopurge

### ISSUE THREAD

**Issue by PLfightX** [RisedSky/discordPandaJS#12]
Le résultat de la commande *randomnumber n'est pas purgé automatiquement

**Comment by PLfightX** [comment]
Sur le random-member aussi je crois

**Comment by RisedSky** [comment]
Je suis en train de travailler dessus, ajout dans pas longtemps (ce soir maybe)

**Comment by RisedSky** [comment]
Bug fixed in the commit : 187ccbf4a9e51f5afa24cf62bbc4f4e56fba79f6
