### ISSUE TITLE
La commande *purge ne sait pas compter

### ISSUE THREAD

**Issue by PLfightX** [RisedSky/discordPandaJS#22]
la commande *purge supprime un message de moins que demandé

How we can reproduce the bug : utilisez la commande *purge 1 après un message

What should happend normally : Le message devrait s'effacer

What actually happen : Il ne s'efface pas :'-(

**Comment by RisedSky** [comment]
I sended a new update commit : adccdbf6daa82fe2f4d532e381bbcc248687049e

**Comment by PLfightX** [comment]
Je confirme, le bug est toujours valable

**Comment by RisedSky** [comment]
Bug fixed in the commit : ca4081cd82cb4e07829f6996ea3a1f8eb54ff5af
