### ISSUE TITLE
README image down

### ISSUE THREAD

**Issue by gadhagod** [RisedSky/discordPandaJS#230]
Description of the issue (more information, be as accurate as possible) :
The README's top.gg image is not working. It says...
> Oops! Something snoopy happened. Visit discordbots.org for help & support.

Maybe this is because the bot was removed from top.gg?

Discordtag (with #, in order to be contacted easily) :
`$(GadhaGod)#4621`

**Comment by RisedSky** [comment]
Hello thanks for your report, effectivity, the bot got removed from top.gg I'll add it again soon

**Comment by gadhagod** [comment]
Sweet
