### ISSUE TITLE
Everything is stuffed in index.js

### ISSUE THREAD

**Issue by gt-c** [RisedSky/discordPandaJS#53]
It appears every command is put in index.js. This makes code _extremely_ unreadable, and no one wants that. You can easily fix this by making a [command handler](https://anidiotsguide_old.gitbooks.io/discord-js-bot-guide/content/coding-guides/a-basic-command-handler.html). If you need help doing this, reply to this comment and I could easily help create one.

**Comment by RisedSky** [comment]
Hello, thanks for your help, i'm currently searching on how it's working and etc..
I was just looking for a command handler yup, it's for the 2.0.0
Can you do an exemple for us ? (if you have the time to !)

**Comment by gt-c** [comment]
Don't worry. I will use my time making it all in one pull request. Please note not to run a loop increasing `online_since`. There is a cool variable called `client.uptime` that returns how many milliseconds the bot has been online

**Comment by gt-c** [comment]
I take this back. This code is absolutely disastrous, moving this neatly will be an extreme pain.

**Comment by gt-c** [comment]
If you want to make a command handler, please try to keep to making the bot one language, or only defining `current_lang` once and putting it in the `client` variable

**Comment by RisedSky** [comment]
Okay, thanks ! :)

**Comment by RisedSky** [comment]
For the current_lang i want to take the lang from the server, so i use the database, you think i could "fix" in the command handler how ?

**Comment by gt-c** [comment]
All right. Let me wrap up everything you need to do before I make it.
1. You need to transfer `current_lang` to a bot variable. If you get the language by guild then as soon as a message is recieved take the client and do: `client.currentLang = ...`. Also it is recommended you only use underscores in const variables, but if that's not your thing I understand.
2. Every other variable should also be transfered into the client, and if possible, defined before a message is recieved and the bot is ready.
3. Remove useless variables and comments that you will never use. I notice that there are a lot of useless comments, and some that are commenting out code. Please remove the useless comments and the code you're not going to use again so I don't have to scroll down as much just to read it. As for useless variables and functions: remove variables and functions you never use, this helps with shortening line length.

**Comment by RisedSky** [comment]
Okay big thanks <3 <3 <3
I will create a new branch to the v2.0.0 ;)

**Comment by RisedSky** [comment]
I created https://github.com/RisedSky/discordPandaJS/commits/bot_2.0.0
I removed some comments useless
i didn't fixed yet some things like the online_since..

**Comment by RisedSky** [comment]
I didn't finished yet, but if you want to start, you can :)

**Comment by TheFallingPie** [comment]
I would like to help you guys out because I have made a modulated bot, I'd suggest you do, even though it might be a little bit heavy on the server side to start off with, you'll get to the point where it'll be the most efficient bot around. You would just have to get the error handlers done and so on.

I'd also suggest to you @RisedSky to make a dashboard with express.js, I can teach you about it. Sorry for this text wall lul but I am just a fellow discord bot developer, if you need any more help, discord username and discriminator is Pie#9196.

**Comment by RisedSky** [comment]
@TheFallingPie Hey, thanks for this reply, I will sure add you on discord :)
See u on discord so :wink:

**Comment by RisedSky** [comment]
@gt-c Can you do the message command handler on **ONLY**  1 command _please_  ? So I have an idea / an exemple to work this evening :relaxed:

**Comment by RisedSky** [comment]
@gt-c Do you have discord ?

**Comment by gt-c** [comment]
Sure

**Comment by RisedSky** [comment]
@kotowi You can define a language in your server, then you do `*lang YourLangHere` and it should be good ! :wink:

**Comment by RisedSky** [comment]
Great news, i'm currently working on the re-work on the bot, and now i finished the "play" command in the command handler, now need to work that on every command and migrate them to the` /commands` directory !

**Comment by RisedSky** [comment]
Here we go b75365f78da7cd585a1ab6eb295bfad3af361b83
I close now this issue.
thanks for the help everyone
